name: Publish

on:
  release:
    types: [published]
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Build Package
      run: |
        python setup.py sdist bdist_wheel
    - name: "List result"
      run: |
        ls -l dist
    - name: "Check long_description"
      run: |
        python -m pip install --upgrade twine
        python -m twine check dist/*
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        password: ${{ secrets.pypi_password }}
